name: autodl
channels:
  - pytorch
dependencies:
  - python=3.5
  - scipy
  - scikit-learn
  - pandas
  - psutil
  - yaml
  - matplotlib
  - pytorch=1.0.1
  - cudatoolkit=10.0
  - torchvision=0.2.2
  - flake8
  - numpy
  - cython
  - pip
  - zip
  - pip:
    - pre-commit
    - tensorflow-gpu==1.13.1
    - hjson
