#!/usr/bin/env python

import inspect
import logging
import os
import sys

from autofolio.autofolio import AutoFolio


cmd_folder = os.path.realpath(
    os.path.abspath(os.path.split(inspect.getfile(inspect.currentframe()))[0])
)
cmd_folder = os.path.realpath(os.path.join(cmd_folder, ".."))
if cmd_folder not in sys.path:
    sys.path.insert(0, cmd_folder)


if __name__ == "__main__":

    # logging.basicConfig(level=logging.INFO)

    af = AutoFolio()
    af.run_cli()
